import React,{useState,useEffect}from'react';
import {Image,Film,AudioLines,Download,FolderOpen,ChevronLeft,ChevronRight,X,Grid2X2,LoaderCircle}from'lucide-react';
import {api}from'./Models';
export function GeneratedLibraryView({refreshKey}){
 const[category,setCategory]=useState('all'),[page,setPage]=useState(1),[data,setData]=useState(null),[error,setError]=useState(''),[preview,setPreview]=useState(null),[loading,setLoading]=useState(false);
 useEffect(()=>{const abort=new AbortController();setLoading(true);fetch('/api/library?category='+category+'&page='+page,{signal:abort.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error);setData(v);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[category,page,refreshKey]);
 return <section className="generated-library"><div className="section-kicker">YOUR CREATIVE COLLECTION</div><div className="library-heading"><div><h1>Generated Library</h1><p>Every idea brought to life. Saved on your computer.</p></div><span>{data?.counts.all||0} creations</span></div><div className="library-tabs" role="tablist" aria-label="Media categories">{[['all','All',Grid2X2],['image','Images',Image],['video','Videos',Film],['audio','Audio',AudioLines]].map(([id,label,Icon])=><button key={id} role="tab" aria-selected={category===id} onClick={()=>{setCategory(id);setPage(1);}}><Icon size={16}/>{label}<span>{data?.counts[id]||0}</span></button>)}</div>{error&&<div className="inline-error" role="alert">{error}</div>}{loading&&<div className="library-loading"><LoaderCircle size={17} className="spin"/>Loading creations…</div>}
 {data?.items.length?<div className="generated-grid">{data.items.map(item=><article className={'creation-card '+item.type} key={item.id}><div className="creation-preview">{item.type==='image'?<button aria-label="Preview image" onClick={()=>setPreview(item)}><img loading="lazy" src={item.url} alt={item.prompt}/></button>:item.type==='video'?<video controls preload="metadata" playsInline src={item.url}/>:<div className="audio-art"><AudioLines size={36}/><span>{item.audioKind==='speech'?'Speech':item.audioKind==='music'?'Music':'Sound'}</span><audio controls preload="metadata" src={item.url}/></div>}</div><div className="creation-info"><span className="creation-model">{item.model||'Local generation'}</span><p title={item.prompt}>{item.prompt}</p><div className="creation-meta"><time>{new Date(item.createdAt).toLocaleDateString()}</time><span>{(item.bytes/1e6).toFixed(1)} MB</span></div><div className="creation-actions"><button title="Show saved file in folder" onClick={async()=>{try{await api('/api/library/'+item.id+'/reveal');}catch(e){setError(e.message);}}}><FolderOpen size={15}/>Show in folder</button><a href={item.url+(item.url.includes('?')?'&':'?')+'download=1'} download={'Wizgard-'+item.filename} title="Download a copy"><Download size={15}/>Download</a></div></div></article>)}</div>:!loading&&<div className="library-empty"><Grid2X2 size={35}/><h3>A little room for imagination.</h3><p>{category==='all'?'Your generated images, videos and audio will appear here.':'No '+({image:'images',video:'videos',audio:'audio'}[category])+' yet.'}</p></div>}
 {data&&data.total>0&&<div className="library-pagination"><span>{(data.page-1)*20+1}–{Math.min(data.page*20,data.total)} of {data.total}</span><div><button aria-label="Previous page" disabled={data.page<=1||loading} onClick={()=>setPage(data.page-1)}><ChevronLeft size={17}/></button><span>Page {data.page} of {data.pages}</span><button aria-label="Next page" disabled={data.page>=data.pages||loading} onClick={()=>setPage(data.page+1)}><ChevronRight size={17}/></button></div></div>}
 {preview&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Generated image" onClick={()=>setPreview(null)}><button className="lightbox-close" aria-label="Close image" onClick={()=>setPreview(null)}><X size={22}/></button><img src={preview.url} alt={preview.prompt}/><a className="primary-button" href={preview.url+'?download=1'} download onClick={e=>e.stopPropagation()}><Download size={16}/>Download a copy</a></div>}
 </section>;
}
