import React, { useState, useRef, useEffect } from 'react';
import { MessageSquare, Image, Film, Mic, Music2, AudioLines, Check, Download, RefreshCw, Trash2, X, ArrowRight, HardDrive, LoaderCircle, Settings2, FolderOpen, ChevronLeft } from 'lucide-react';
export const capabilityIcons = { chat:MessageSquare,image:Image,video:Film,speech:Mic,music:Music2,sfx:AudioLines };
export async function api(path,body) {const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})});const data=await r.json();if(!r.ok)throw new Error(data.error||'The operation failed.');return data;}
const gb=n=>(n/1e9).toFixed(1)+' GB';
function Progress({job,onCancel}) {
 if(!job)return null;
 const running=['running','cancelling'].includes(job.status);
 const percent=job.percent??job.filePercent??null;
 return <div className={'install-progress '+job.status} role="status" aria-live="polite"><div className="install-progress-heading">{running?<LoaderCircle size={19} className="spin"/>:job.status==='complete'?<Check size={19}/>:<RefreshCw size={19}/>}<strong>{running?'Preparing your workspace':job.status==='complete'?'Ready to create':job.status==='error'?'Installation needs attention':'Installation stopped'}</strong>{running&&<button className="subtle-button" onClick={onCancel} disabled={job.status==='cancelling'}>{job.status==='cancelling'?'Stopping…':'Stop'}</button>}</div><p>{job.message}</p>{running&&<><div className={'install-track '+(percent===null?'indeterminate':'')} role="progressbar" aria-label="Model installation" aria-valuenow={percent??undefined} aria-valuemin={0} aria-valuemax={100}><i style={percent===null?{}:{width:percent+'%'}}/></div><div className="install-caption"><span>{job.phase==='runtime'?'Installing engine dependencies':job.phase==='verifying'?'Verifying downloaded files':'Model download'} · {job.completed||0} / {job.ids?.length||1} ready</span><strong>{percent===null?'Preparing…':percent+'%'}</strong></div></>}</div>;
}
export function ModelManagerView({state,output,onRefresh,onClose,setup=false}) {
 const shell=useRef(null);
 const [selected,setSelected]=useState(['chat']),[step,setStep]=useState(1),[error,setError]=useState(''),[pending,setPending]=useState(false),[remove,setRemove]=useState(null),[folder,setFolder]=useState(output?.custom?output.outputLocation:''),[saved,setSaved]=useState(false);
 useEffect(()=>{if(shell.current)shell.current.scrollTop=0;},[step]);
 useEffect(()=>{
  if(setup)return;
  const panel=shell.current;
  const target=remove?panel?.querySelector('[role="alertdialog"]'):panel;
  const controls=()=>Array.from(target?.querySelectorAll('button:not(:disabled),input:not(:disabled),a[href],select')||[]).filter(e=>e.getClientRects().length);
  controls()[0]?.focus();
  const key=e=>{if(e.key==='Tab'){const items=controls();if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};
  panel?.addEventListener('keydown',key);return()=>panel?.removeEventListener('keydown',key);
 },[setup,remove]);
 const running=pending||state?.operating||['running','cancelling'].includes(state?.job?.status);
 const models=state?.models||[],chosen=models.filter(m=>selected.includes(m.id));
 async function act(path,body){setError('');setPending(true);try{await api(path,body);onRefresh();return true;}catch(e){setError(e.message);return false;}finally{setPending(false);}}
 const card=m=>{const Icon=capabilityIcons[m.id],checking=state.checking,status=!m.installed?m.weights?'Engine needed':'Not installed':checking?'Checking updates…':m.update==='current'?'Up to date':m.update==='available'?'Update available':m.update==='unknown'?'Unable to check':'Not checked';return <article className={'model-card '+(selected.includes(m.id)&&setup?'selected ':'')+(!m.supported?'unsupported':'')} key={m.id}>
  <div className="model-card-top"><span className={'capability-icon '+m.id}><Icon size={24}/></span>{setup?<input type="checkbox" aria-label={'Install '+m.name} checked={selected.includes(m.id)} disabled={!m.supported||running} onChange={e=>setSelected(old=>e.target.checked?[...old,m.id]:old.filter(id=>id!==m.id))}/>:<span className={'model-status '+(m.installed?'installed':'')}>{m.installed?<Check size={12}/>:<HardDrive size={12}/>} {status}</span>}</div>
  <span className="model-purpose">{m.purpose}</span><h3>{m.name}</h3><div className="model-subtitle">{m.subtitle}</div><p>{m.description}</p><div className="model-size"><HardDrive size={13}/>{gb(m.bytes)} <span>model files</span></div>{m.requirement&&<small className="model-requirement">{m.requirement}</small>}
  {!setup&&<div className="model-card-actions">{m.installed?<><label className="active-control"><button className={'toggle '+(m.active?'on':'')} role="switch" aria-checked={m.active} aria-label={'Activate '+m.name} disabled={running} onClick={()=>act('/api/models/active',{id:m.id,active:!m.active})}><span/></button>{m.active?'Active':'Inactive'}</label><button className="icon-button" aria-label={'Update '+m.name} title={m.update==='current'?'Model is up to date':'Install latest model version'} disabled={running||m.update==='current'||checking} onClick={()=>act('/api/models/install',{ids:[m.id]})}><RefreshCw size={16}/></button><button className="icon-button model-remove" aria-label={'Uninstall '+m.name} title="Uninstall model" disabled={running} onClick={()=>{setError('');setRemove(m);}}><Trash2 size={16}/></button></>:<button className="install-button" disabled={running||!m.supported} onClick={()=>act('/api/models/install',{ids:[m.id]})}><Download size={15}/>{m.weights?'Finish installation':'Install model'}</button>}</div>}
 </article>;};
 return <div ref={shell} className={setup?'setup-shell':'modal-backdrop models-backdrop'} onClick={setup?undefined:onClose}><section className={'models-panel '+(setup?'onboarding':'')} role={setup?undefined:'dialog'} aria-modal={setup?undefined:true} aria-label={setup?'Set up Wizgard':'Manage Models'} onClick={e=>e.stopPropagation()}>
  <header className="models-header"><div className="models-brand"><img src="/wizgard-icon.png" alt=""/><strong>Wizgard</strong><span>YOUR LOCAL CREATIVE STUDIO</span></div>{!setup&&<button className="icon-button" aria-label="Close model manager" onClick={onClose}><X size={22}/></button>}</header>
  <div className="models-intro"><div><div className="section-kicker">{setup?'A LITTLE SETUP. A LOT OF POSSIBILITY.':'YOUR MODELS. YOUR CHOICE.'}</div><h1>{setup?(step===1?'What would you like to create?':'Make room for a little magic.'):'Manage Models'}</h1><p>{setup?'Choose the tools for your workspace. Start with one, add more whenever inspiration strikes.':'Install the models you need, keep them current, and choose which ones Wizgard can use.'}</p></div>{!setup&&<button className="subtle-button check-updates" disabled={state.checking||running} onClick={()=>act('/api/models/check')}><RefreshCw size={15} className={state.checking?'spin':''}/>{state.checking?'Checking…':'Check for updates'}</button>}</div>
  {error&&<div className="inline-error" role="alert">{error}</div>}
  <Progress job={state.job} onCancel={()=>act('/api/models/cancel')}/>
  {setup&&step===2?<div className="setup-review"><div className="review-icon"><Download size={32}/></div><h2>Your workspace, on this computer.</h2><p>{chosen.map(m=>m.name).join(' · ')}</p><div className="review-size">{gb(chosen.reduce((n,m)=>n+(m.weights?0:m.bytes),0))}<span>model downloads, plus engine dependencies</span></div><p>Internet is needed for installation. Afterward, generation runs locally. Downloads can be stopped and resumed.</p><div className="review-models">{chosen.map(m=>{const Icon=capabilityIcons[m.id];return <span key={m.id}><Icon size={16}/>{m.purpose}</span>;})}</div></div>:<div className="model-grid">{models.map(card)}</div>}
  {!setup&&<section className="output-settings"><div className="output-label"><FolderOpen size={21}/><div><h3>Generated files location</h3><p>New images, videos and audio are saved in a Wizgard subfolder. Existing files stay where they are.</p></div></div><form onSubmit={async e=>{e.preventDefault();setSaved(false);if(await act('/api/output',{outputLocation:folder}))setSaved(true);}}><input aria-label="Generated files location" value={folder} placeholder={output?.outputLocation||'Use the default project folder'} onChange={e=>{setFolder(e.target.value);setSaved(false);}}/><button className="primary-button" disabled={running}>{saved?<><Check size={15}/>Saved</>:'Save location'}</button></form><small>Use an absolute folder path. Leave empty to use the project’s default output folder.</small></section>}
  <footer className="models-footer"><p><HardDrive size={14}/>{setup?'Only selected models will be installed.':'Update status is checked on launch. Models update only when you choose.'}</p>{setup?<div>{step===2&&<button className="subtle-button" disabled={running} onClick={()=>setStep(1)}><ChevronLeft size={15}/>Back</button>}<button className="primary-button" disabled={!chosen.length||running} onClick={()=>step===1?setStep(2):act('/api/models/install',{ids:selected})}>{step===1?'Next':running?'Installing…':'Install selected models'}<ArrowRight size={16}/></button></div>:<button className="primary-button" onClick={onClose}>Back to workspace<ArrowRight size={16}/></button>}</footer>
  {setup&&<div className="setup-credit">An AI Tool developed by <strong>Karmikal Apps</strong> © 2026</div>}
  {remove&&<div className="modal-backdrop clear-backdrop"><section className="clear-modal" role="alertdialog" aria-modal="true" aria-labelledby="remove-model-title"><div className="clear-icon"><Trash2 size={23}/></div><h2 id="remove-model-title">Uninstall {remove.name}?</h2><p>This removes its downloaded model files. Your chats and generated media will be kept. You can install the model again later.</p>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="clear-actions"><button className="cancel-button" disabled={running} onClick={()=>setRemove(null)}>Cancel</button><button className="danger-button" disabled={running} onClick={async()=>{if(await act('/api/models/uninstall',{id:remove.id,confirmation:'UNINSTALL_'+remove.id}))setRemove(null);}}>Uninstall model</button></div></section></div>}
 </section></div>;
}
