import React,{useState} from 'react';
import {ListOrdered,Clock,ArrowUp,ArrowDown,Pause,Play,Square,ArrowUpRight} from 'lucide-react';
import {api} from './Models';
const duration=seconds=>seconds==null?'Learning…':seconds<60?Math.round(seconds)+'s':seconds<3600?Math.floor(seconds/60)+'m '+Math.round(seconds%60)+'s':Math.floor(seconds/3600)+'h '+Math.floor(seconds%3600/60)+'m';
export function GenerationQueue({jobs,onUpdate,onOpen}){
 const [pending,setPending]=useState(null),[error,setError]=useState('');
 const waiting=jobs.filter(j=>j.reorderable);
 async function action(job,command){setPending(job.id);setError('');try{onUpdate(await api('/api/jobs/'+job.id+'/'+command));}catch(e){setError(e.message);}finally{setPending(null);}}
 async function move(job,delta){const ids=waiting.map(j=>j.id),i=ids.indexOf(job.id),target=i+delta;if(i<0||target<0||target>=ids.length)return;[ids[i],ids[target]]=[ids[target],ids[i]];setPending(job.id);setError('');try{onUpdate(await api('/api/jobs/reorder',{ids}));}catch(e){setError(e.message);}finally{setPending(null);}}
 return <section className="generation-queue"><div className="section-kicker">YOUR LOCAL ENGINES</div><div className="library-heading"><div><h1>Generation Queue</h1><p>Keep creating while your local models work.</p></div><span>{jobs.length} pending</span></div><p className="queue-explanation">Qwen processes one response at a time. Media uses the engine exclusively. Reorder waiting jobs with the arrows; a running job keeps its place.</p>{error&&<div className="inline-error" role="alert">{error}</div>}
 {!jobs.length?<div className="library-empty"><ListOrdered size={34}/><h3>Ready for your next idea.</h3><p>New requests appear here while they run or wait.</p></div>:<ol className="queue-list">{jobs.map(job=>{const index=waiting.findIndex(j=>j.id===job.id);return <li key={job.id} className={'queue-card '+job.state}><div className="queue-card-top"><span className={'queue-state '+job.state}>{job.state==='queued'?'Queued · '+job.queuePosition:job.state==='paused'?'Paused':'Running'}</span><span className="queue-mode">{job.mode}</span><button title="Open conversation" onClick={()=>onOpen(job.conversationId)}><ArrowUpRight size={17}/></button></div><h3>{job.title}</h3><p className="queue-prompt">{job.prompt}</p><p className="queue-status">{job.state==='paused'?'Paused until you resume.':job.status}</p>{job.progress!=null&&<div className="queue-progress" role="progressbar" aria-label="Generation progress" aria-valuenow={job.progress} aria-valuemin={0} aria-valuemax={100}><i style={{width:job.progress+'%'}}/></div>}<div className="queue-timing"><span><Clock size={13}/>Elapsed {duration(job.elapsedSeconds)}</span><span>Processing {duration(job.activeSeconds)}</span><span>{job.state==='running'?'Remaining ≈ '+duration(job.remainingSeconds):job.state==='paused'?'Estimate paused':job.blocked?'Waiting for paused engine':'Starts in ≈ '+duration(job.waitSeconds)}</span></div><div className="queue-actions">{job.reorderable&&<div><button aria-label={'Move '+job.title+' up'} disabled={!!pending||index===0} onClick={()=>move(job,-1)}><ArrowUp size={14}/>Up</button><button aria-label={'Move '+job.title+' down'} disabled={!!pending||index===waiting.length-1} onClick={()=>move(job,1)}><ArrowDown size={14}/>Down</button></div>}<div><button disabled={!!pending||job.sharedPause} onClick={()=>action(job,job.state==='paused'?'resume':'pause')}>{job.state==='paused'?<Play size={14}/>:<Pause size={14}/>} {job.state==='paused'?'Resume':'Pause'}</button><button disabled={!!pending} onClick={()=>action(job,'stop')}><Square size={13}/>Stop</button></div></div></li>;})}</ol>}
 <p className="queue-estimate-note">Estimates learn from recent jobs with similar settings on this computer. Prompt complexity, model loading and other apps affect timing. Paused time is excluded from processing time.</p></section>;
}
