import React,{useEffect,useState} from 'react';
import {Activity,Cpu,MemoryStick,Monitor,X} from 'lucide-react';
import './resources.css';
const percent=n=>Number.isFinite(n)?n.toFixed(1)+'%':'—';
const gib=n=>Number.isFinite(n)?(n/1073741824).toFixed(1)+' GiB':'—';
function Meter({icon:Icon,label,value,level,history,title}){return <div className="resource-meter" title={title}><Icon size={14}/><span>{label}</span><strong>{value}</strong><svg viewBox="0 0 100 24" preserveAspectRatio="none" aria-hidden="true"><polyline points={history.map((n,i)=>(i*100/23)+','+(22-Math.min(100,n)*.2)).join(' ')}/></svg><i className="resource-level"><b style={{width:Math.max(0,Math.min(100,level||0))+'%'}}/></i></div>;}
export function ResourceBar({onClose}){
 const [sample,setSample]=useState(null),[history,setHistory]=useState({cpu:Array(24).fill(0),gpu:Array(24).fill(0),ram:Array(24).fill(0)}),[failed,setFailed]=useState(false);
 useEffect(()=>{let cancelled=false,timer;const controller=new AbortController();async function tick(){try{const r=await fetch('/api/resources',{signal:controller.signal});if(!r.ok)throw new Error();const d=await r.json();if(cancelled)return;setSample(d);setFailed(false);setHistory(h=>({cpu:[...h.cpu.slice(1),d.cpuPercent||0],gpu:[...h.gpu.slice(1),d.gpuPercent||0],ram:[...h.ram.slice(1),d.ramBytes/d.ramTotal*100||0]}));}catch{if(!cancelled)setFailed(true);}if(!cancelled)timer=setTimeout(tick,2000);}tick();return()=>{cancelled=true;clearTimeout(timer);controller.abort();};},[]);
 return <div className="resource-bar" aria-label="Live resource usage"><div className="resource-brand"><Activity size={15}/><span>WIZGARD LIVE</span><i className={failed?'offline':''}/></div><Meter icon={Cpu} label="CPU" value={percent(sample?.cpuPercent)} level={sample?.cpuPercent} history={history.cpu} title="Wizgard and its child engines, as a percentage of total CPU capacity."/><Meter icon={Monitor} label={sample?.gpuScope==='device'?'GPU · DEVICE':'GPU'} value={percent(sample?.gpuPercent)} level={sample?.gpuPercent} history={history.gpu} title={sample?.gpuScope==='device'?'Whole NVIDIA device utilization; per-app GPU usage is unavailable on this platform.':'Wizgard process-tree GPU utilization where supported; — means unavailable.'}/><Meter icon={MemoryStick} label="RAM" value={gib(sample?.ramBytes)} level={sample?.ramBytes/sample?.ramTotal*100} history={history.ram} title="Sum of resident/working-set memory for Wizgard and its child engines. Shared memory may be counted more than once."/>{sample?.vramBytes!=null&&<span className="resource-vram" title="GPU memory reported for Wizgard's compute processes">VRAM <strong>{gib(sample.vramBytes)}</strong></span>}<span className="resource-poll">{failed?'UNAVAILABLE':sample?'~2s refresh':'SAMPLING'}</span><button type="button" onClick={onClose} aria-label="Hide resource usage"><X size={15}/></button></div>;
}
